// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewStat = "review_stats"

// ReviewStat 评价统计表
type ReviewStat struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                      // 主键
	CreateBy     string     `gorm:"column:create_by;not null;comment:创建方标识" json:"create_by"`                          // 创建方标识
	UpdateBy     string     `gorm:"column:update_by;not null;comment:更新方标识" json:"update_by"`                          // 更新方标识
	CreateAt     time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt     time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeleteAt     *time.Time `gorm:"column:delete_at;comment:逻辑删除标记" json:"delete_at"`                                  // 逻辑删除标记
	TotalCount   int32      `gorm:"column:total_count;not null;comment:评价总数" json:"total_count"`                       // 评价总数
	AvgScore     int32      `gorm:"column:avg_score;not null;comment:平均评分" json:"avg_score"`                           // 平均评分
	PositiveRate float64    `gorm:"column:positive_rate;not null;default:0.00;comment:好评率 (%)" json:"positive_rate"`   // 好评率 (%)
	NegativeRate float64    `gorm:"column:negative_rate;not null;default:0.00;comment:差评率 (%)" json:"negative_rate"`   // 差评率 (%)
	HasMediaRate float64    `gorm:"column:has_media_rate;not null;default:0.00;comment:带图率 (%)" json:"has_media_rate"` // 带图率 (%)
	SpuID        int64      `gorm:"column:spu_id;not null;comment:商品ID" json:"spu_id"`                                 // 商品ID
	StoreID      string     `gorm:"column:store_id;not null;comment:店铺ID" json:"store_id"`                             // 店铺ID
	ExtJSON      string     `gorm:"column:ext_json;not null;comment:信息扩展" json:"ext_json"`                             // 信息扩展
	CtrlJSON     string     `gorm:"column:ctrl_json;not null;comment:控制扩展" json:"ctrl_json"`                           // 控制扩展
}

// TableName ReviewStat's table name
func (*ReviewStat) TableName() string {
	return TableNameReviewStat
}
