// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-service/internal/biz"
	"review-service/internal/conf"
	"review-service/internal/data"
	"review-service/internal/server"
	"review-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, elasticsearch *conf.Elasticsearch, kafka *conf.Kafka, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	esClient, err := data.NewESClient(elasticsearch)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	mqClient := data.NewMQClient(kafka)
	dataData, cleanup, err := data.NewData(db, logger, esClient, client, mqClient)
	if err != nil {
		return nil, nil, err
	}
	workerPool := server.NewWorkerPool(logger)
	reviewRepo := data.NewReviewRepo(dataData, logger, workerPool)
	reviewUsecase := biz.NewReviewUsecase(reviewRepo, logger, workerPool)
	reviewService := service.NewReviewService(reviewUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, reviewService, logger)
	httpServer := server.NewHTTPServer(confServer, reviewService, logger)
	registrar := server.NewRegistrar(registry)
	goroutineManager := server.NewGoroutineManager(logger, reviewUsecase)
	app := newApp(logger, grpcServer, httpServer, registrar, workerPool, goroutineManager)
	return app, func() {
		cleanup()
	}, nil
}
